execute as @s[hasitem={item=ds:water_fists},tag=itemUse:ds:water_fists] at @s run function fighting/yuji/use_water_heavy
execute as @s[hasitem={item=ds:water_fists},scores={punch=1..}] at @s run function fighting/yuji/use_water_heavy
execute as @s[hasitem={item=ds:water_fists}] at @s run function fighting/yuji/water_attacks

tag @s[tag=itemUse:ds:yuji_fists,tag=!wepclick] add wepclick
execute as @s[tag=itemUse:ds:yuji_fists] at @s run function fighting/yuji/use_yuji_heavy
execute as @s[tag=sukunacursedtool] at @s run function sukunacursedtool_off

tag @s[scores={Stun=0,Disabled2=0,Sneaking=1..,wep5=0,punch=1,Energy=50..},hasitem={item=ds:yuji_fists,location=slot.weapon.mainhand}] add wep5
execute as @s[scores={Stun=0,Disabled2=0,Sneaking=1..,wep5=1..,punch=1,Energy=50..},hasitem={item=ds:yuji_fists,location=slot.weapon.mainhand}] at @s run playsound note.pling @a ~~~ 0.05 0.4
execute as @s[scores={Stun=0,Disabled2=0,Sneaking=1..,wep5=1..,punch=1,Energy=50..},hasitem={item=ds:yuji_fists,location=slot.weapon.mainhand}] at @s run tellraw @s {"rawtext":[{"text":"§cDivergent Strike is on cooldown: §e"},{"score":{"name": "@p","objective": "wep5"}},{"text":"§c."}]}
scoreboard players set @s[scores={Stun=0,Disabled2=0,Sneaking=1..,wep5=0,punch=1,Energy=50..},hasitem={item=ds:yuji_fists,location=slot.weapon.mainhand}] move 26
scoreboard players set @s[scores={Stun=0,Disabled2=0,Sneaking=1..,wep5=0,punch=1,Energy=50..},hasitem={item=ds:yuji_fists,location=slot.weapon.mainhand}] wep5 800
scoreboard players remove @s[scores={Sneaking=1..,punch=1,Energy=50..,move=26},hasitem={item=ds:yuji_fists,location=slot.weapon.mainhand}] Energy 50

scoreboard players set @s[scores={BasicM1=1..,Stun=0}] M1Reset 25
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..6}] AfterAnim 10
scoreboard players set @s[scores={BasicM1s=7..}] Disabled 22
scoreboard players set @s[scores={BasicM1=1..2,BasicM1s=6..,Stun=0}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=7..}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=1..,Stun=1..}] BasicM1s 0

scoreboard players set @s[scores={BasicM1=1}] BasicM1 0

effect @s weakness 1 99 true

scoreboard players random @s[scores={BasicM1=5,BasicM1s=1..,Stun=0},tag=!heavenlyrestriction] blackflashchance 1 200
scoreboard players set @s[scores={BasicM1=5,BasicM1s=1..,Stun=0},tag=blackflashrig,tag=!heavenlyrestriction] blackflashchance 7

scoreboard players add @s[scores={detect_left=1,BasicM1=0,BasicM1s=0..6,Disabled=0,detect_sneak=0}] BasicM1s 1

execute as @s[scores={BasicM1=5..,BasicM1s=6}] at @s unless entity @e[tag=!Frames,r=2.5,rm=0.1,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run scriptevent ds:knockback 2


execute as @s[scores={BasicM1=5..}] run function stance_animate_yuji
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=1,Stun=0}] BasicM1 6
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=2,Stun=0}] BasicM1 6
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=3,Stun=0}] BasicM1 8
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=4,Stun=0}] BasicM1 9
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=5,Stun=0}] BasicM1 8
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=6,Stun=0}] BasicM1 11

scoreboard players set @s[scores={BasicM1=4,BasicM1s=1..}] atk 2


execute as @s[scores={BasicM1=5..,BasicM1s=1..5}] at @s positioned ^^^1.85 run execute as @e[tag=!Frames,r=1.8,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s @s
execute as @s[scores={BasicM1=5..,BasicM1s=1..5}] at @s positioned ^^^1.85 run execute as @e[tag=!Frames,r=1.8,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=5..,BasicM1s=1..5},c=1]

execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^1.85 run scoreboard players operation @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a ~~~ 1 0.75
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^1.85 if entity  @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 1.95 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^1.85 run damage @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 suicide
execute as @s[scores={BasicM1=3,BasicM1s=1..2}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 16
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 9
execute as @s[scores={BasicM1=3,BasicM1s=3}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=3}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6


execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^3.85 run scoreboard players operation @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^3.85 if entity  @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 1.95 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^3.85 run damage @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 suicide
execute as @s[scores={BasicM1=3,BasicM1s=1..2}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 16
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 9
execute as @s[scores={BasicM1=3,BasicM1s=3}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6


scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=6}] atk 2
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a ~~~ 1 0.5
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s run tp @s ~~~
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 run scoreboard players operation @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=6}] at @s positioned ^^^2.85 run execute as @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s @s
execute as @s[scores={BasicM1=3..7,BasicM1s=6}] at @s positioned ^^^2.85 run execute as @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=6},c=1]
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 if entity @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 1.25 10000
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 run damage @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 4 suicide
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 15
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Flourish 8

execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^1^1.25 run particle ds:heavy_impact1
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^1^1.25 run particle ds:heavy_impact2
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^1^1.25 run particle ds:heavy_impact3

execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 run scoreboard players operation @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=6}] at @s positioned ^^^4.85 run execute as @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s @s
execute as @s[scores={BasicM1=3..7,BasicM1s=6}] at @s positioned ^^^4.85 run execute as @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=6},c=1]
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 if entity @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 1.25 10000
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 run scoreboard players add @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 run damage @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 4 suicide
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 run scoreboard players add @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 run scoreboard players add @e[tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 15
execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s positioned ^^^4.85 run scoreboard players add @e[type=!item,tag=!Frames,r=5.849,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Flourish 8

execute as @s[scores={BasicM1=3,BasicM1s=6}] at @s run function damages/blunt_damage
execute as @s[scores={BasicM1=3,BasicM1s=1..5}] at @s run function damages/blunt_damage

scoreboard players set @s[scores={BasicM1=1..3,BasicM1s=1..6}] BasicM1 0