playanimation @s[scores={move=35..36}] animation.calamity.ab2

playanimation @s[scores={move=31..,Stun=1..}] animation.stunned
scoreboard players set @s[scores={move=31..,Stun=1..}] move 2

tag @s[scores={move=1..2},tag=wep2] remove wep2

scoreboard players set @s[scores={move=1..30}] Frames 4
scoreboard players set @s[scores={move=1..}] Move 4

scoreboard players random @s[scores={move=4},tag=!heavenlyrestriction] blackflashchance 1 200
scoreboard players set @s[scores={move=4},tag=blackflashrig,tag=!heavenlyrestriction] blackflashchance 7

execute as @s[scores={move=31}] at @s run particle ds:leap
execute as @s[scores={move=31}] at @s run particle ds:ground_slam1
execute as @s[scores={move=31}] at @s run particle ds:ground_slam2
execute as @s[scores={move=31}] at @s run playsound mob.wither.shoot @a[r=33] ~~~ 99999 0.5 99999
execute as @s[scores={move=31}] at @s run playsound mob.enderdragon.flap @a[r=33] ~~~ 99999 2 99999

execute as @s[scores={move=6..30}] at @s run  camerashake add @a[r=5] 0.1 0.08
execute as @s[scores={move=6..30}] at @s run particle ds:sprint
execute as @s[scores={move=6..30}] at @s run scriptevent ds:knockback 3
execute as @s[scores={move=6..}] at @s if block ~~-0.25~ air run scriptevent ds:downfall
execute as @s[scores={move=6..30}] at @s positioned ^^^2.5 if entity @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run scoreboard players set @s move 5


playanimation @s[scores={move=4..5}] animation.calamity.ab2b

scoreboard players set @s[scores={move=4..5}] atk 2
execute as @s[scores={move=4..5}] at @s  run tp @s @s
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run camerashake add @a[r=10] 2 0.15
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:punch1 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:punch2 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:punch3 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:punch4 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:ground_slam2 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:large_impact1 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run particle ds:large_impact2 ~~1~
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run playsound mob.blood1 @a[r=50] ~~1~ 9999 1.25 9999
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run execute as @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run playsound mob.punch1 @a[r=50] ~~1~ 9999 1.25 9999
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run damage @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 20 suicide
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run  scoreboard players operation @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run scoreboard players add @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 5
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run scoreboard players add @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 15
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run scoreboard players add @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 35
execute as @s[scores={move=4}] at @s positioned ^^^2.5 run playanimation @e[r=2.45,tag=!Frames,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:boss_knockback1,type=!ds:boss_knockback_small,type=!ds:mahoraga_knockback1,type=!ds:mahoraga_knockback2,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] animation.stunned i 1
execute as @s[scores={move=4}] at @s run function damages/blunt_damage
